# This is a basic workflow that is manually triggered

name: Manual workflow to call an API

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apiCall:
    runs-on: ubuntu-latest
    steps:
    - name: Call an API
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://c01-sg.integrate.boomi.com/ws/rest/personDetails/v1/personDetails/'
        method: 'POST'
        contentType: 'application/json'
        data: '{"name":"Ashmita","age":18,"role":"Software Engineer"}'
        username: trainingashmitasawant-D9P8J7.YG1FA4
        password: 9bfd395e-361d-41ad-8107-154f5938402f
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
