# This is a basic workflow that is manually triggered

name: Manual workflow to call an API

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apiCall:
    runs-on: ubuntu-latest
    env:
       name: DevelopmentEnv
       username: ${{ secrets.BOOMI_USERNAME }}
       
    steps:
    - name: SetVariables
      run: echo "The API key is:${{env.username}}"
    
