# This is a basic workflow that is manually triggered

name: Manual workflow to call an API

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apiCall:
    runs-on: ubuntu-latest
    
    steps:
    - name: SetVariables
      env:
       name: DevelopmentEnv
       username: ${{ secrets.BOOMI_USERNAME }}
       password: ${{ secrets.BOOMI_PASSWORD }}
    
    - name: AtomQuery
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/Atom/query'
        method: 'POST'
        contentType: 'application/json'
        data: '{"QueryFilter" : {"expression" :{"argument" : ["ATOM"], "operator" : "EQUALS", "property" : "type"}}}'
        username: ${{env.username}}
        password: ${{env.password}}
        
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
