# This is a basic workflow that is manually triggered

name: Manual workflow to deploy a package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apiCall:
    environment: Dev
    env:
       BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
       BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
    runs-on: ubuntu-latest
    
       
    steps:
    
    - name: DeployPackage
      id: packageDeploy
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/DeployedPackage'
        method: 'POST'
        contentType: 'application/json'
        data: '{"environmentId" : "cb0f570d-001e-44ea-be4e-f31010264365",   "packageId" : "8a2671a1-6887-49e4-aff7-a9c1213bbff7"}'
        username: ${{env.BOOMI_USERNAME}}
        password: ${{env.BOOMI_PASSWORD}}
        
    - name: Show Response
      run: echo ${{ steps.packageDeploy.outputs.response }}
