name: "test"
on: # rebuild any PRs and main branch changes
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: get name
      id: name
      uses: ./
      with: 
        path: 'TestJson.json'
        prop_path: 'name'
    - run: echo ${{steps.name.outputs.prop}}        
        
    - name: get nested json property
      id: get_json_property
      uses: ./
      with: 
        path: 'TestJson.json'
        prop_path: 'age'

    - run: echo ${{steps.get_json_property.outputs.prop}}     
