name: Test JSON read
on: 
  workflow_dispatch

jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
           JSON=$(cat .github/workflows/TestJson.json)
           echo "::set-output name=matrix::${JSON//'%'/'%25'}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build
