# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  runScript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run.sh script
      run: chmod +x .github/workflows/test.sh
           echo ${{run}}
