# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.runScript.outputs.test }}

    steps:
    - uses: actions/checkout@v2
    - name: Run.sh script
      id: runScript
      run: |
           chmod +x .github/workflows/test.sh
           .github/workflows/test.sh

      
  
    
  
           
      
   
    
