# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.runScript.outputs.test }}

    steps:
    - uses: actions/checkout@v2
    - name: Run.sh script
      id: runScript
      run: echo "::set-output name=test::chmod +x .github/workflows/getAllEnvironments.sh"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
    
  
           
      
   
    
