# This is a basic workflow that is manually triggered

name: testWrite

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Print Hello
    - uses: actions/checkout@v2
      with:
          path: './ProcessDetails_CSV.txt'
    - id: printHello
    - run: echo "123" > ./ProcessDetails_CSV.txt
           
