# This is a basic workflow that is manually triggered

name: testWrite

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: write
        env:
          AWS_HOST: "abc"
        run: |
             ProcessDetails=$(cat ./ProcessDetails_CSV.txt)
             echo $ProcessDetails
