# This is a basic workflow that is manually triggered

name: Manual workflow to call an API

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apiCall:
    environment: Dev
    env:
       BOOMI_USERNAME: ${{ secrets.BOOMI_USERNAME }}
       BOOMI_PASSWORD: ${{ secrets.BOOMI_PASSWORD }}
    runs-on: ubuntu-latest
    
       
    steps:
    - name: SetVariables
      run: echo "The API key is:${{env.username}}"
    
    - name: AtomQuery
      id: myRequest
      uses: satak/webrequest-action@master
      with:
          url: 'https://api.boomi.com/api/rest/v1/neosalpha-SSL1AK/PackagedComponent'
          method: POST
          payload: '{"componentId": "0a558e5f-69f2-460b-95e3-fe5ba308b1e7","packageVersion":"1.25", "notes":"Package for deployment" }'
          headers: '{"Accept": "application/json", "Content-Type":"application/json"}'
          username: ${{env.BOOMI_USERNAME}}
          password: ${{env.BOOMI_PASSWORD}}
    - name: Show Response  
      run: |
           $output = $(echo ${{ steps.myRequest.outputs.output }})
           echo $output
           
        
 
