name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.setProcessInfo.outputs.arr}}
    steps:
      - uses: actions/checkout@v1

      # This step will create "an array" of strings, e.g. "path1 path2 path3"
      - name: array
        id: arr
        run: |
          arr=()
          for i in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          do
            if [[ $i == *"path1"* ]]; then
              arr+=("path1")
            fi
            if [[ $i == *"path2"* ]]; then
              arr+=("path2")
            fi
          done
          echo ::set-output name=arr::${arr[@]}
          
  fetchArr:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: SetVariables
       id: showVariable
       run:   echo ${{needs.arr.outputs.output1}}
             

     
      
