name: Test

on:
  push

jobs:
  loopcheck:
   strategy:
      matrix:
        scssfiles: ["fileone.scss","file2.sass"]
   runs-on: ubuntu-latest
    
   steps:
     - name: test
       run: |
             echo ${{matrix.scssfiles}}
     
      
