name: Test JSON Read
on:
  workflow_dispatch

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat ./TestJson.json`
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).processName[0]}}"
